### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by epugh** [trulia/thoth#5]
https://github.com/trulia/thoth/wiki/Thoth-Modules

The link to Thoth ML is busted, you get a 404.  Maybe not yet public?

**Comment by dbraga** [comment]
@epugh Yes, thoth ml module is still not public  :smile:  . We are working on the cleanup and we will release it in the upcoming weeks, stay tuned!

**Comment by epugh** [comment]
Great.   I’m blogging about what I saw at LuceneRevolution, and one of the things that made me excited about Thoth was that evidence that ML isn’t just “Look, we have a open source ML library”, but “look, open source projects are leveraging ML to be smarter”.   It’s proof that techniques like ML are filtering out into the wider industry.

Eric

> On Nov 21, 2014, at 4:04 PM, Damiano Braga notifications@github.com wrote:
> 
> @epugh https://github.com/epugh Yes, thoth ml module is still not public   . We are working on the cleanup and we will release it in the upcoming weeks, stay tuned!
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/trulia/thoth/issues/5#issuecomment-64037413.

---

Eric Pugh | Principal | OpenSource Connections, LLC | 434.466.1467 | http://www.opensourceconnections.com http://www.opensourceconnections.com/ | My Free/Busy http://tinyurl.com/eric-cal  
Co-Author: Apache Solr 3 Enterprise Search Server http://www.packtpub.com/apache-solr-3-enterprise-search-server/book 
This e-mail and all contents, including attachments, is considered to be Company Confidential unless explicitly stated otherwise, regardless of whether attachments are marked as such.

**Comment by dbraga** [comment]
@epugh Awesome! that's exactly what moved us to work on a machine learning component after all the data that we collect with Thoth. You should link the article, it will be an interesting read!
